version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: messenger-app
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
    links:
      - db
    volumes:
      - app:/home/app
    restart: always
    networks:
      - messenger-db-network
    command: npm run start:prod
  db:
    image: postgres:14.5-alpine
    container_name: db
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - messenger-db-network
volumes:
  app:
  postgres:
networks:
  messenger-db-network:
    name: messenger-db-network
    driver: bridge
